/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flightSuretyAppSol from "./FlightSuretyApp.sol";
export type { flightSuretyAppSol };
import type * as flightSuretyDataBackupSol from "./FlightSuretyDataBackup.sol";
export type { flightSuretyDataBackupSol };
export type { FlightSuretyData } from "./FlightSuretyData";
