/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlightSuretyApp } from "./FlightSuretyApp";
export type { FlightSuretyData } from "./FlightSuretyData";
