/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  FlightSuretyData,
  FlightSuretyDataInterface,
} from "../../../contracts/FlightSuretyApp.sol/FlightSuretyData";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "flightCode",
        type: "string",
      },
    ],
    name: "creditInsurees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "airlineAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "registerAirline",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "insuredPassenger",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FlightSuretyData__factory {
  static readonly abi = _abi;
  static createInterface(): FlightSuretyDataInterface {
    return new Interface(_abi) as FlightSuretyDataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FlightSuretyData {
    return new Contract(address, _abi, runner) as unknown as FlightSuretyData;
  }
}
